In [1]:
import numpy as np

In [7]:
#qustion1
array3=np.random.rand(2,3)

In [9]:
array4=np.random.rand(2,3)

In [10]:
sumarray=array3+array3

In [11]:
sumarray

array([[1.38867363, 1.06035215, 1.14507003],
       [0.07849808, 1.45820063, 1.77574057]])

In [12]:
#qustion2
a = np.array([[2.5, 3.8, 1.5],[4.7, 2.9, 1.56]])
a.dtype="int"

In [13]:
a.dtype

dtype('int32')

In [14]:
#qustion3
b = np.array([[1, 0, 0],[1, 1, 1],[0, 0, 0]])
b.dtype="bool"

In [15]:
b

array([[ True, False, False, False, False, False, False, False, False,
        False, False, False],
       [ True, False, False, False,  True, False, False, False,  True,
        False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False]])

In [2]:
#qustion4
array1=np.full((2,3),5)

In [3]:
array1

array([[5, 5, 5],
       [5, 5, 5]])

In [16]:
#qustion5
v=np.random.seed(42)
M = np.random.randint(10, size=(2,2,10))
print(M)


[[[6 3 7 4 6 9 2 6 7 4]
  [3 7 7 2 5 4 1 7 5 1]]

 [[4 0 9 5 8 0 9 2 6 3]
  [8 2 4 2 6 4 8 6 1 3]]]


In [28]:
M[:,:,-1]

array([[4, 1],
       [3, 3]])

In [52]:
M[0,1,::2]

array([3, 7, 5, 1, 5])

In [55]:
M[:,:,1::2]

array([[[3, 4, 9, 6, 4],
        [7, 2, 4, 7, 1]],

       [[0, 5, 0, 2, 3],
        [2, 2, 4, 6, 3]]])

In [74]:
y=np.random.normal(2,10,(2,3))

In [75]:
y.var(axis=1,dtype=float)

array([  5.88078519, 105.80963555])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices